# fly.toml app configuration file generated for green-snowflake-7899 on 2023-08-22T09:09:29+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "green-snowflake-7899"
primary_region = "arn"

[build]
  [build.args]
    NODE_VERSION = "16.20.2"

[http_service]
  internal_port = 8080
  http_checks = []
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[deploy]
  release_command = "npm run build"

[processes]
  app = "node app.js"

